"""User Type Added

Revision ID: b6ef487c8d79
Revises: 54e9a4327abd
Create Date: 2026-07-17 16:23:38.799386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6ef487c8d79'
down_revision: Union[str, Sequence[str], None] = '54e9a4327abd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('type', sa.String(), nullable=True))

    # Backfill existing rows so they get the default 'user' type
    op.execute("UPDATE users SET type = 'user' WHERE type IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'type')
    # ### end Alembic commands ###
